name: $[counter('c',1)]

trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: calqulus
    type: git
    name: app-calqulus
    ref: refs/heads/main
  - repository: calqulus-ci
    type: git
    name: app-calqulus-ci-templates
    ref: main
  - repository: toolbelt
    type: git
    name: Dev/app-calqulus-toolbelt
    ref: refs/heads/main

extends:
  template: base-pipelines.yml@calqulus-ci

